

services:
  localstack:
    image: localstack/localstack:3.3.0
    container_name: localstack
    hostname: localstack
    ports:
      - 4566:4566
    volumes:
      - ./localstack/root/.aws/credentials:/root/.aws/credentials
      - ./localstack/startup.sh:/startup.sh
    environment:
      - LOCALSTACK_SERVICES=s3
    entrypoint: /startup.sh
    healthcheck:
      test: curl -s http://localhost:4566/_localstack/health | jq -e '.services.s3 == "available" or .services.s3 == "running"'
      interval: 30s
      timeout: 10s
      start_period: 3m
      # start_interval: 10s
      retries: 20

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.33.0
    container_name: azurite
    hostname: azurite
    ports:
      # blob
      # CredentialType: StorageSharedKeyCredential
      # AccountName: devstoreaccount1
      # AccountKey: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      # ServiceUri: http://localhost:10000/devstoreaccount1
      - 10000:10000 # blob
    # healthcheck:
    #   test: curl -f http://localhost:10000/devstoreaccount1 || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  oss-emulator:
    build:
      context: ./oss-emulator
    container_name: oss-emulator
    hostname: oss-emulator
    ports:
      - 8280:8280
